{{- if .Values.api.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "isaac-app.api.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "isaac-app.api.fullname" . }}
  minReplicas: {{ .Values.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.api.autoscaling.maxReplicas }}
  behavior:
    scaleUp:
      {{- toYaml .Values.api.autoscaling.scaleUp | nindent 6 }}
    scaleDown:
      {{- toYaml .Values.api.autoscaling.scaleDown | nindent 6 }}
  metrics:
    {{- if .Values.api.autoscaling.targetMemory }}
    - type: ContainerResource
      container: {{ .Chart.Name }}
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetMemory }}
    {{- end }}
    {{- if .Values.api.autoscaling.targetCPU }}
    - type: ContainerResource
      container: {{ .Chart.Name }}
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetCPU }}
    {{- end }}
{{- end }}
