---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "isaac-app.name" . }}-content-indices
  labels:
    {{- include "isaac-app.labels" . | nindent 4 }}
data:
  content-indices.properties: |
    live={{ .Values.contentRepo.liveSha }}
