apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "isaac-app.etl.fullname" . }}
  labels:
    {{- include "isaac-app.labels" . | nindent 4 }}
    {{- include "isaac-app.etl.selectorLabels" . | nindent 4 }}
  {{- with .Values.etl.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.etl.replicaCount }}
  selector:
    matchLabels:
      {{- include "isaac-app.etl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "isaac-app.etl.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.etl.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.etl.image.repository }}/{{ .Values.etl.image.repository }}:{{ .Values.etl.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.etl.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SEGUE_CONFIG_LOCATION
              value: /local/data/conf/segue-config.properties
            - name: JAVA_OPTIONS
              value: {{ .Values.etl.javaOptions }}
          livenessProbe:
            httpGet:
              path: /isaac-api/api/etl/ping
              port: http
          readinessProbe:
            httpGet:
              path: /isaac-api/api/etl/ping
              port:  http
          startupProbe:
            httpGet:
              path: /isaac-api/api/etl/ping
              port:  http
            periodSeconds: 10
            failureThreshold: 15
          resources:
            {{- toYaml .Values.etl.resources | nindent 12 }}
          volumeMounts:
            - name: isaac-config
              mountPath: /local/data/conf
            - name: isaac-content-key
              mountPath: /local/data/ssh-key
            - name: git-content
              mountPath: /local/data/git
            - name: content-indices
              mountPath: /local/data/content
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v3.6.2
          args:
            - --repo={{ .Values.contentRepo.url }}
            - --root=/local/data/git
            - --depth={{ .Values.contentRepo.depth }}
            - --wait={{ .Values.contentRepo.wait }}
            - --ssh
            - --ssh-key-file=/local/data/ssh-key/content-key
            - --ssh-known-hosts=false
            - --add-user
          volumeMounts:
            - name: isaac-content-key
              mountPath: /local/data/ssh-key
            - name: git-content
              mountPath: /local/data/git
          resources:
            {{- toYaml .Values.etl.gitSync.resources | nindent 12 }}
      initContainers:
        - name: git-sync-init
          image: registry.k8s.io/git-sync/git-sync:v3.6.2
          args:
            - --one-time
            - --repo={{ .Values.contentRepo.url }}
            - --root=/local/data/git
            - --depth={{ .Values.contentRepo.depth }}
            - --wait={{ .Values.contentRepo.wait }}
            - --ssh
            - --ssh-key-file=/local/data/ssh-key/content-key
            - --ssh-known-hosts=false
            - --add-user
          volumeMounts:
            - name: isaac-content-key
              mountPath: /local/data/ssh-key
            - name: git-content
              mountPath: /local/data/git
          resources:
            {{- toYaml .Values.etl.gitSync.resources | nindent 12 }}
      volumes:
        - name: isaac-config
          secret:
            secretName: {{ .Values.etl.config.secretName }}
        - name: isaac-content-key
          secret:
            defaultMode: 0400
            secretName: {{ .Values.etl.config.contentKeySecretName }}
        - name: git-content
          emptyDir: {}
        - name: content-indices
          configMap:
            name: {{ include "isaac-app.name" . }}-content-indices

      {{- with .Values.etl.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.etl.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.etl.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
