# Default values for isaac-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""
contentRepo:
  url: git@github.com:isaaccomputerscience/isaac-content.git
  depth: 1000
  wait: 60
  liveSha: fbb01c97c3210f77b4420ed043ebbac80f7200d3
  taskPeriodSeconds: 60

isaac-app-fe:
  image:
    registry: null # Set to null so we can use `repository` for Argo image updater's `image-name` annotation.
    repository: gchr.io/isaaccomputerscience/isaac-react-app-cs
    tag: v1.0.0
  service:
    type: ClusterIP
  containerPorts:
    http: 80
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: www.non-prod.isaaccomputerscience.org
    path: "/"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      # NOTE: Using configuration-snippet in a multitenant cluster has security risks, see https://github.com/kubernetes/ingress-nginx/issues/7837
      # Since we are installing this in a non multitenant cluster and we assume all invididuals with access to the ArgoCD repo are admins, we
      # decided this CVE does not present a security risk. A more secure workaround is in development and should be migrated to once it is
      # completed: https://github.com/kubernetes/ingress-nginx/issues/7811
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Content-Security-Policy: default-src 'self' wss://*.isaaccomputerscience.org https://*.isaaccomputerscience.org https://www.google-analytics.com https://www.youtube-nocookie.com https://www.youtube.com; object-src 'none'; frame-src 'self' https://*.isaaccomputerscience.org  https://www.youtube-nocookie.com; img-src 'self' data: https://*.isaaccomputerscience.org https://www.google-analytics.com https://*.tile.openstreetmap.org https://developers.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://*.isaaccomputerscience.org https://fonts.gstatic.com;";
  resources: {}
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPU: 60
    targetMemory: 50

isaac-cdn:
  image:
    registry: null
    repository: ghcr.io/isaaccomputerscience/isaac-cdn
    tag: v1.0.0
  service:
    type: ClusterIP
  containerPorts:
    http: 80
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: cdn.non-prod.isaaccomputerscience.org
    path: "/"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    extraTls:
      - hosts:
          - cdn.non-prod.isaaccomputerscience.org
        secretName: cdn-isaac
  resources: {}

isaac-app-renderer:
  image:
    registry: null
    repository: ghcr.io/isaaccomputerscience/isaac-react-app-cs-renderer
    tag: v1.0.0
  service:
    type: ClusterIP
  containerPorts:
    http: 80
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: editor-preview.non-prod.isaaccomputerscience.org
    path: "/"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      # NOTE: Using configuration-snippet in a multitenant cluster has security risks, see https://github.com/kubernetes/ingress-nginx/issues/7837
      # Since we are installing this in a non multitenant cluster and we assume all invididuals with access to the ArgoCD repo are admins, we
      # decided this CVE does not present a security risk. A more secure workaround is in development and should be migrated to once it is
      # completed: https://github.com/kubernetes/ingress-nginx/issues/7811
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Content-Security-Policy: default-src 'self' https://*.isaaccomputerscience.org https://www.youtube-nocookie.com https://www.youtube.com; object-src 'none'; frame-src 'self' https://*.isaaccomputerscience.org https://www.youtube-nocookie.com; img-src 'self' data: https://*.isaaccomputerscience.org https://*.tile.openstreetmap.org https://developers.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://*.isaaccomputerscience.org https://fonts.gstatic.com; frame-ancestors 'self' https://*.isaaccomputerscience.org;";
    extraTls:
      - hosts:
          - editor-preview.non-prod.isaaccomputerscience.org
        secretName: editor-preview-isaac
  resources: {}

isaac-content-editor:
  image:
    registry: null
    repository: ghcr.io/isaaccomputerscience/isaac-content-editor
    tag: v1.0.0
  service:
    type: ClusterIP
  containerPorts:
    http: 80
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: content-editor.non-prod.isaaccomputerscience.org
    path: "/"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      # NOTE: Using configuration-snippet in a multitenant cluster has security risks, see https://github.com/kubernetes/ingress-nginx/issues/7837
      # Since we are installing this in a non multitenant cluster and we assume all invididuals with access to the ArgoCD repo are admins, we
      # decided this CVE does not present a security risk. A more secure workaround is in development and should be migrated to once it is
      # completed: https://github.com/kubernetes/ingress-nginx/issues/7811
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Content-Security-Policy: default-src 'self' https://*.isaaccomputerscience.org https://www.youtube-nocookie.com https://www.youtube.com https://api.github.com object-src 'none'; frame-src 'self' https://*.isaaccomputerscience.org https://www.youtube-nocookie.com; img-src 'self' data: https://*.isaaccomputerscience.org https://*.tile.openstreetmap.org https://developers.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://*.isaaccomputerscience.org https://fonts.gstatic.com;";
    extraTls:
      - hosts:
          - content-editor.non-prod.isaaccomputerscience.org
        secretName: content-editor-isaac
  extraEnvVars:
    - name: REACT_APP_SITE
      value: CS
    - name: REACT_APP_CLIENT_ID
      value: f1540415e26cc2a5765a
    - name: REACT_APP_AUTH_URL
      value: https://editor-auth.non-prod.isaaccomputerscience.org/access_token
    - name: REACT_APP_GITHUB_OWNER
      value: isaaccomputerscience
    - name: REACT_APP_CONTENT_REPO
      value: isaac-content
    - name: REACT_APP_PREVIEW_HOST
      value: https://editor-preview.non-prod.isaaccomputerscience.org
    - name: REACT_APP_API_STAGING_HOST
      value: https://www.staging.non-prod.isaaccomputerscience.org
    - name: REACT_APP_API_HOST
      value: https://www.non-prod.isaaccomputerscience.org
  resources: {}

isaac-code-editor:
  image:
    registry: null
    repository: ghcr.io/isaaccomputerscience/isaac-code-editor
    tag: v1.0.0
  service:
    type: ClusterIP
  containerPorts:
    http: 80
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: code-editor.non-prod.isaaccomputerscience.org
    path: "/"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    extraTls:
      - hosts:
          - code-editor.non-prod.isaaccomputerscience.org
        secretName: code-editor-isaac
  resources: {}

elastic-search:
  protocol: http
  createCert: false
  imageTag: 7.17.6
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: false
      xpack.security.transport.ssl.enabled: false
      ingest.geoip.downloader.enabled: false
  clusterName: isaac-cs-content
  replicas: 1
  persistence:
    enabled: false

  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: isaac-secrets
          key: elasticsearch-pw
  resources: {}

api:
  name: "api"
  image:
    repository: ghcr.io/isaaccomputerscience/isaac-api
    tag: v1.0.0
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  javaOptions: "-Xmx2g"
  config:
    secretName: isaac-secrets
    contentKeySecretName: isaac-content-key
  prometheusExport:
    enabled: true
    path: /
    port: 9966
  service:
    type: ClusterIP
    port: 80
  deployment:
    annotations:
      secret.reloader.stakater.com/reload: "isaac-secrets,isaac-content-key"
      configmap.reloader.stakater.com/reload: "isaac-app-content-indices"
  ingress:
    enabled: enabled
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/rewrite-target: /isaac-api/$2
      nginx.ingress.kubernetes.io/proxy-cookie-path: /isaac-api /
      nginx.ingress.kubernetes.io/enable-cors: "true"
    hosts:
      - host: www.non-prod.isaaccomputerscience.org
        paths:
          - path: /api/([^/]+)/(.*)$
            pathType: Prefix
    tls:
      - secretName: www-isaac
        hosts:
          - www.non-prod.isaaccomputerscience.org
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  gitSync:
    resources: {}
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPU: 50
    targetMemory: 50
    scaleUp:
      stabilizationWindowSeconds: 0
    scaleDown:
      stabilizationWindowSeconds: 300

etl:
  name: "etl"
  replicaCount: 1
  image:
    repository: ghcr.io/isaaccomputerscience/isaac-api-etl
    tag: v1.0.0
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  javaOptions: "-Xmx2g"
  config:
    apiVersion: v3.3.2-snapshot
    secretName: isaac-secrets
    contentKeySecretName: isaac-content-key
  service:
    type: ClusterIP
    port: 80
  deployment:
    annotations:
      secret.reloader.stakater.com/reload: "isaac-secrets,isaac-content-key"
      configmap.reloader.stakater.com/reload: "isaac-app-content-indices"
  ingress:
    enabled: false
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  gitSync:
    resources: {}

eqChecker:
  name: "equality-checker"
  replicaCount: 1
  image:
    repository: ucamcldtg/equality-checker
    tag: latest
    pullPolicy: Always
  imagePullSecrets: []
  podAnnotations: {}
  podSecurityContext: {}
  # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
  # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

chemChecker:
  name: "chemistry-checker"
  replicaCount: 1
  image:
    repository: ucamcldtg/chemistry-checker
    tag: latest
    pullPolicy: Always
  imagePullSecrets: []
  podAnnotations: {}
  podSecurityContext: {}
  # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

editorAuth:
  name: "editor-auth"
  replicaCount: 1
  image:
    repository: ghcr.io/isaaccomputerscience/isaac-editor-auth
    tag: v1.0.0
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  config:
    allowOriginHeader: https://content-editor.non-prod.isaaccomputerscience.org
    secretName: isaac-editor-auth-secrets
  service:
    type: ClusterIP
    port: 80
  deployment:
    annotations:
      secret.reloader.stakater.com/reload: "isaac-editor-auth-secrets"
  ingress:
    enabled: enabled
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: editor-auth.non-prod.isaaccomputerscience.org
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: editor-auth-isaac
        hosts:
          - editor-auth.non-prod.isaaccomputerscience.org
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

shortUrlIngress:
  name: "short-url-ingress"
  enabled: enabled
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.non-prod.isaaccomputerscience.org$request_uri
    nginx.ingress.kubernetes.io/server-snippet: |
      location /q/ {
            rewrite ^/q/(.*)$ https://www.non-prod.isaaccomputerscience.org/questions/$1 permanent;
      }

      location /bq/ {
          rewrite ^/bq/(.*)$ https://www.non-prod.isaaccomputerscience.org/questions/$1?utm_source=book&utm_medium=book&utm_campaign=workbook_link;
      }

      location /eq/ {
          rewrite ^/eq/(.*)$ https://www.non-prod.isaaccomputerscience.org/questions/$1?utm_source=ebook&utm_medium=ebook&utm_campaign=workbook_link;
      }

      location /c/ {
          rewrite ^/c/(.*)$ https://www.non-prod.isaaccomputerscience.org/concepts/$1 permanent;
      }

      location /p/ {
          rewrite ^/p/(.*)$ https://www.non-prod.isaaccomputerscience.org/pages/$1 permanent;
      }

      location /t/ {
          rewrite ^/t/(.*)$ https://www.non-prod.isaaccomputerscience.org/topics/$1 permanent;
      }

      location /e/ {
          rewrite ^/e/(.*)$ https://www.non-prod.isaaccomputerscience.org/events/$1 permanent;
      }

      location /a/ {
          rewrite ^/a/(.*)$ https://www.non-prod.isaaccomputerscience.org/assignment/$1 permanent;
      }

      location /g/ {
          rewrite ^/g/(.*)$ https://www.non-prod.isaaccomputerscience.org/gameboards#$1 permanent;
      }

      location /join/ {
          rewrite ^/join/(.*)$ https://www.non-prod.isaaccomputerscience.org/account?authToken=$1 permanent;
      }
  host: short.non-prod.isaaccomputerscience.org
